# Generated by Django 3.2.5 on 2021-07-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'STUDENT_INFO',
            },
        ),
    ]
