# Generated by Django 3.2.5 on 2021-07-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('exp', models.IntegerField()),
                ('salary', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateTimeField()),
                ('role', models.CharField(choices=[('SE', 'SOFTWARE ENG'), ('TL', 'TEAM LEAD'), ('SSE', 'SNR.SOFTWARE ENG'), ('CEO', 'CEO')], max_length=4)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'REGISTER_INFO',
            },
        ),
    ]
